# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-04 08:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppStock',
            fields=[
                ('pk_stock', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('stockname', models.CharField(blank=True, max_length=100, null=True)),
                ('tradetype', models.CharField(blank=True, max_length=100, null=True)),
                ('isdisabled', models.IntegerField(blank=True, null=True)),
                ('istop', models.IntegerField(blank=True, null=True)),
                ('sortno', models.IntegerField(blank=True, null=True)),
                ('createtime', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'app_stock',
            },
        ),
    ]
